#-- Lattice Semiconductor Corporation Ltd.
#-- Map run script generated by Radiant

set ret 0
if {[catch {

if {![file exists {C:/Git/E155Project/FPGA/Radient/Passthrough/Passthrough/impl_1}]} {
  file mkdir {C:/Git/E155Project/FPGA/Radient/Passthrough/Passthrough/impl_1}
}
cd {C:/Git/E155Project/FPGA/Radient/Passthrough/Passthrough/impl_1}

sys_set_attribute -gui on -msg {C:/Git/E155Project/FPGA/Radient/Passthrough/Passthrough/promote.xml}
msg_load {C:/Git/E155Project/FPGA/Radient/Passthrough/Passthrough/promote.xml}
des_set_project_udb -in {Passthrough_impl_1_syn.udb} -out {Passthrough_impl_1_map.udb} -milestone map -pm ice40tp
des_set_reference_udb -clean
map_set_option {pdc_file "C:/Git/E155Project/FPGA/Src/FPGApins.pdc"}
# map option
map_set_option { report_symbol_cross_reference false report_signal_cross_reference false   ignore_constraint_errors false }
map_run

} out]} {
   puts $out
   set ret 1
}
exit -force ${ret}
